import SwiftUI

struct PeriodDetailView: View {
    let period: BudgetPeriod

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: PPSpacing.xl) {
                // Status badge
                HStack {
                    statusBadge
                    if period.isAutoGenerated {
                        Label("Auto-generated", systemImage: "arrow.triangle.2.circlepath")
                            .font(.ppCaption)
                            .foregroundColor(.ppTextTertiary)
                            .padding(.horizontal, PPSpacing.sm)
                            .padding(.vertical, 4)
                            .background(Color.ppSurface)
                            .clipShape(RoundedRectangle(cornerRadius: PPRadius.full))
                    }
                    Spacer()
                }

                // Date range card
                VStack(alignment: .leading, spacing: PPSpacing.lg) {
                    Text("DATE RANGE")
                        .font(.ppOverline)
                        .foregroundColor(.ppTextSecondary)
                        .tracking(1)

                    HStack(spacing: PPSpacing.xxl) {
                        dateColumn("Start", date: period.startDate)
                        dateColumn("End", date: period.endDate)
                        daysColumn
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(PPSpacing.xl)
                .background(Color.ppCard)
                .clipShape(RoundedRectangle(cornerRadius: PPRadius.lg))
                .overlay(
                    RoundedRectangle(cornerRadius: PPRadius.lg)
                        .stroke(Color.ppBorder, lineWidth: 1)
                )

                // Metrics card
                VStack(alignment: .leading, spacing: PPSpacing.lg) {
                    Text("METRICS")
                        .font(.ppOverline)
                        .foregroundColor(.ppTextSecondary)
                        .tracking(1)

                    HStack(spacing: PPSpacing.xxl) {
                        metricItem(
                            value: "\(period.transactionCount)",
                            label: "Transactions"
                        )
                        metricItem(
                            value: "\(Int(period.budgetUsedPercentage))%",
                            label: "Budget Used"
                        )
                    }

                    if period.budgetUsedPercentage > 0 {
                        GeometryReader { geo in
                            ZStack(alignment: .leading) {
                                RoundedRectangle(cornerRadius: 4)
                                    .fill(Color.ppBorder)
                                    .frame(height: 6)

                                RoundedRectangle(cornerRadius: 4)
                                    .fill(period.budgetUsedPercentage > 100 ? Color.ppDestructive : Color.ppPrimary)
                                    .frame(width: geo.size.width * min(period.budgetUsedPercentage / 100, 1.0), height: 6)
                            }
                        }
                        .frame(height: 6)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(PPSpacing.xl)
                .background(Color.ppCard)
                .clipShape(RoundedRectangle(cornerRadius: PPRadius.lg))
                .overlay(
                    RoundedRectangle(cornerRadius: PPRadius.lg)
                        .stroke(Color.ppBorder, lineWidth: 1)
                )
            }
            .padding(PPSpacing.lg)
        }
        .background(Color.ppBackground)
        .navigationTitle(period.name)
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(Color.ppBackground, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
    }

    // MARK: - Status Badge

    private var statusBadge: some View {
        Text(period.statusText.uppercased())
            .font(.ppCaption)
            .fontWeight(.bold)
            .foregroundColor(statusColor)
            .padding(.horizontal, PPSpacing.md)
            .padding(.vertical, 4)
            .background(statusColor.opacity(0.15))
            .clipShape(RoundedRectangle(cornerRadius: PPRadius.full))
    }

    private var statusColor: Color {
        switch period.status {
        case .active: return .ppCyan
        case .ended: return .ppTextTertiary
        case .upcoming: return .ppAmber
        case .unknown: return .ppTextTertiary
        }
    }

    // MARK: - Date Column

    private func dateColumn(_ label: String, date: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(label)
                .font(.ppCaption)
                .foregroundColor(.ppTextTertiary)
            Text(formatDateString(date))
                .font(.ppHeadline)
                .foregroundColor(.ppTextPrimary)
        }
    }

    private var daysColumn: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Duration")
                .font(.ppCaption)
                .foregroundColor(.ppTextTertiary)
            Text("\(daysBetween) days")
                .font(.ppHeadline)
                .foregroundColor(.ppTextPrimary)
        }
    }

    // MARK: - Metric Item

    private func metricItem(value: String, label: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(value)
                .font(.ppTitle)
                .foregroundColor(.ppTextPrimary)
            Text(label)
                .font(.ppCaption)
                .foregroundColor(.ppTextSecondary)
        }
    }

    // MARK: - Helpers

    private var daysBetween: Int {
        guard let start = DateFormatter.apiDate.date(from: period.startDate),
              let end = DateFormatter.apiDate.date(from: period.endDate) else { return 0 }
        return Calendar.current.dateComponents([.day], from: start, to: end).day ?? 0
    }

    private func formatDateString(_ dateString: String) -> String {
        guard let date = DateFormatter.apiDate.date(from: dateString) else { return dateString }
        let fmt = DateFormatter()
        fmt.dateFormat = "MMM d, yyyy"
        return fmt.string(from: date)
    }
}
