import Foundation

struct BudgetPeriod: Codable, Identifiable {
    let id: UUID
    let name: String
    let startDate: String  // "2026-02-01" — NaiveDate comes as string
    let endDate: String
    let isAutoGenerated: Bool
    let transactionCount: Int
    let budgetUsedPercentage: Double

    // MARK: - Computed helpers

    var startDateFormatted: Date? {
        Self.apiDateFormatter.date(from: startDate)
    }

    var endDateFormatted: Date? {
        Self.apiDateFormatter.date(from: endDate)
    }

    var dateRangeText: String {
        guard let start = startDateFormatted, let end = endDateFormatted else {
            return "\(startDate) - \(endDate)"
        }
        let fmt = DateFormatter()
        fmt.dateFormat = "MMM d"
        return "\(fmt.string(from: start)) - \(fmt.string(from: end))"
    }

    var status: PeriodStatus {
        let today = Date()
        guard let start = startDateFormatted, let end = endDateFormatted else { return .unknown }

        if today < start { return .upcoming }
        if today > end { return .ended }
        return .active
    }

    var statusText: String {
        switch status {
        case .active: return String(localized: "Active")
        case .ended: return String(localized: "Ended")
        case .upcoming: return String(localized: "Upcoming")
        case .unknown: return ""
        }
    }

    private static let apiDateFormatter: DateFormatter = {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        return fmt
    }()
}

enum PeriodStatus {
    case active, ended, upcoming, unknown
}
