import Foundation

struct BudgetPeriod: Codable, Identifiable {
    let id: UUID
    let name: String
    let startDate: String  // "2026-02-01" — NaiveDate comes as string
    let periodType: String // "duration" | "manualEndDate"
    let length: Int
    let remainingDays: Int?
    let numberOfTransactions: Int
    let percentageOfTargetUsed: Double?
    let status: String?    // "active" | "upcoming" | "past"
    let totalSpent: Int64
    let totalBudgeted: Int64

    // MARK: - Backward compatibility computed properties

    /// Computed from startDate + length (days)
    var endDate: String {
        guard let start = startDateFormatted else { return startDate }
        guard let end = Calendar.current.date(byAdding: .day, value: length, to: start) else { return startDate }
        return Self.apiDateFormatter.string(from: end)
    }

    var transactionCount: Int { numberOfTransactions }

    var budgetUsedPercentage: Double { percentageOfTargetUsed ?? 0 }

    var isAutoGenerated: Bool { false }

    // MARK: - Computed helpers

    var startDateFormatted: Date? {
        Self.apiDateFormatter.date(from: startDate)
    }

    var endDateFormatted: Date? {
        Self.apiDateFormatter.date(from: endDate)
    }

    var dateRangeText: String {
        guard let start = startDateFormatted, let end = endDateFormatted else {
            return "\(startDate) - \(endDate)"
        }
        let fmt = DateFormatter()
        fmt.dateFormat = "MMM d"
        return "\(fmt.string(from: start)) - \(fmt.string(from: end))"
    }

    var periodStatus: PeriodStatus {
        switch status {
        case "active": return .active
        case "past": return .ended
        case "upcoming": return .upcoming
        default:
            // Fallback to date-based calculation
            let today = Date()
            guard let start = startDateFormatted, let end = endDateFormatted else { return .unknown }
            if today < start { return .upcoming }
            if today > end { return .ended }
            return .active
        }
    }

    var statusText: String {
        switch periodStatus {
        case .active: return String(localized: "Active")
        case .ended: return String(localized: "Ended")
        case .upcoming: return String(localized: "Upcoming")
        case .unknown: return ""
        }
    }

    private static let apiDateFormatter: DateFormatter = {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        return fmt
    }()
}

enum PeriodStatus {
    case active, ended, upcoming, unknown
}
